require 'application_system_test_case'

class BoardsTest < ApplicationSystemTestCase
  setup do
    @board = boards(:one)
  end

  test 'visiting the homepage' do
    visit root_url
    assert_selector 'h2', text: 'Latest 10 generated boards'
    assert_selector 'a', text: 'View all generated boards'
  end

  test 'visiting the index' do
    visit boards_url
    assert_selector 'th > a', text: 'Name'
    assert_selector 'th > a', text: 'Width'
    assert_selector 'th > a', text: 'Height'
    assert_selector 'th > a', text: 'Bombs'
    assert_selector 'th > a', text: 'Generated by'
    assert_selector 'th > a', text: 'Generated at'
  end

  test 'should create board' do
    visit boards_url
    click_on 'Generate New Board'

    fill_in 'Bombs', with: @board.bombs
    fill_in 'Email', with: @board.email
    fill_in 'Height', with: @board.height
    fill_in 'Name', with: @board.name
    fill_in 'Width', with: @board.width
    click_on 'Create Board'

    assert_text 'Board was successfully created'
    click_on 'Go back'
  end

  test 'viewing bomb' do
    visit board_url(@board)

    assert_selector "#grid_#{@board.id}"
    assert_selector 'h1', text: "#{@board.name} (#{@board.width}x#{@board.height})"
  end
end
